"""add language field in post

Revision ID: 739e1061e37d
Revises: 899f821913b3
Create Date: 2019-03-13 23:32:13.509114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739e1061e37d'
down_revision = '899f821913b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
