"""empty message

Revision ID: 899f821913b3
Revises: df473a28aee7
Create Date: 2019-03-04 16:06:20.200251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899f821913b3'
down_revision = 'df473a28aee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
